"""Background ETL: tail aurum_2 journal JSONL files into paper_events.

Strategy:
  * Poll /aurum_2/journal once per second (configurable). On Docker bind
    mounts from a Windows host, inotify events do not propagate reliably,
    so we always poll. Poll cost is one stat() per known file.
  * For each known file, seek to last byte offset, read appended bytes,
    split on newline, parse each line as JSON, batch up to AURUM_ETL_BATCH_SIZE
    rows or 1 second window — whichever comes first — then bulk INSERT
    ... ON CONFLICT (event_id) DO NOTHING.
  * After each successful batch, update etl_checkpoints[source='paper_journal']
    with last_processed_file, last_processed_ts, last_event_id.
  * Pre-contract lines (no event_id): synthesize UUID5 from (file, line, ts,
    type) so replays are idempotent. Mark event_id_synthetic=true.
  * File rotation: detected by FILENAME date (journal_YYYYMMDD.jsonl), not
    host-clock — the integration target showed two files for the same UTC
    day because the brain's host clock was off. Walk all *.jsonl files
    sorted lexicographically.
  * Resume: on startup, read checkpoint. Re-scan its file from the start
    — duplicates are absorbed by ON CONFLICT. (Storing byte offsets would
    be marginally faster but adds a contract that the file never gets
    truncated; the dedup-by-event_id approach is simpler and correct.)
  * Errors:
      - Malformed JSON line: increment counter, skip line, continue.
      - DB error: retry with exponential backoff up to 3 times per batch,
        then re-raise (which causes the task to crash; uvicorn restarts
        the process via the container's CMD).
      - Missing journal dir: warn + sleep + retry. Don't crash backend.
"""

from __future__ import annotations

import asyncio
import json
import logging
import re
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

from sqlalchemy.dialects.postgresql import insert
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import get_settings
from app.db.models import EtlCheckpoint, PaperEvent
from app.db.session import SessionLocal

logger = logging.getLogger(__name__)

ETL_SOURCE = "paper_journal"
_FILENAME_RE = re.compile(r"^journal_\d{8}\.jsonl$")
# Stable namespace UUID for synthetic event_ids. Different from
# uuid.NAMESPACE_OID so it's clear these were generated by the platform ETL.
_SYNTHETIC_NS = uuid.UUID("a7e3a7e3-aaaa-bbbb-cccc-aurum2platform00".replace("aurum2platform00", "0123456789ab"))


def _list_journal_files(directory: Path) -> list[Path]:
    if not directory.exists():
        return []
    return sorted(p for p in directory.iterdir() if _FILENAME_RE.match(p.name))


def _parse_ts(value: Any) -> datetime | None:
    if not isinstance(value, str):
        return None
    try:
        return datetime.fromisoformat(value.replace(" ", "T", 1))
    except ValueError:
        return None


def _synthetic_event_id(source_file: str, source_line: int, ts: str, event_type: str) -> uuid.UUID:
    name = f"{source_file}:{source_line}:{ts}:{event_type}"
    return uuid.uuid5(_SYNTHETIC_NS, name)


def _parse_line(
    line: str, *, source_file: str, source_line: int
) -> dict[str, Any] | None:
    """Return a dict ready for INSERT, or None if the line is unprocessable.

    A line with valid JSON but missing 'type' / 'ts' is also skipped — the
    journal contract requires both, and a row without them is unsearchable.
    """
    line = line.strip()
    if not line:
        return None
    try:
        obj = json.loads(line)
    except json.JSONDecodeError:
        logger.warning("etl: malformed JSON in %s:%d", source_file, source_line)
        return None
    if not isinstance(obj, dict):
        return None
    event_type = obj.get("type") or obj.get("event_type")
    ts_raw = obj.get("ts")
    if not event_type or not ts_raw:
        logger.warning("etl: missing type/ts in %s:%d", source_file, source_line)
        return None
    ts = _parse_ts(ts_raw)
    if ts is None:
        logger.warning("etl: unparseable ts %r in %s:%d", ts_raw, source_file, source_line)
        return None
    raw_event_id = obj.get("event_id")
    if raw_event_id:
        try:
            event_id = uuid.UUID(str(raw_event_id))
            synthetic = False
        except ValueError:
            event_id = _synthetic_event_id(source_file, source_line, str(ts_raw), event_type)
            synthetic = True
    else:
        event_id = _synthetic_event_id(source_file, source_line, str(ts_raw), event_type)
        synthetic = True
    return {
        "event_id": event_id,
        "ts": ts,
        "instrument": obj.get("instrument"),
        "event_type": str(event_type),
        "payload": obj,
        "source_file": source_file,
        "source_line": source_line,
        "event_id_synthetic": synthetic,
    }


async def _insert_batch(session: AsyncSession, rows: list[dict[str, Any]]) -> int:
    if not rows:
        return 0
    stmt = insert(PaperEvent).values(rows).on_conflict_do_nothing(
        index_elements=[PaperEvent.event_id]
    )
    result = await session.execute(stmt)
    return result.rowcount or 0


async def _update_checkpoint(
    session: AsyncSession,
    *,
    source_file: str,
    last_ts: datetime,
    last_event_id: uuid.UUID,
) -> None:
    stmt = insert(EtlCheckpoint).values(
        source=ETL_SOURCE,
        last_processed_file=source_file,
        last_processed_ts=last_ts,
        last_event_id=last_event_id,
    ).on_conflict_do_update(
        index_elements=[EtlCheckpoint.source],
        set_={
            "last_processed_file": source_file,
            "last_processed_ts": last_ts,
            "last_event_id": last_event_id,
            "updated_at": datetime.now(timezone.utc),
        },
    )
    await session.execute(stmt)


async def _load_checkpoint(session: AsyncSession) -> EtlCheckpoint | None:
    return await session.get(EtlCheckpoint, ETL_SOURCE)


async def _process_file(
    session: AsyncSession, path: Path, *, batch_size: int
) -> tuple[int, int]:
    """Read entire file, batch-insert rows. Returns (parsed, inserted).

    Idempotent — re-processing the same file is safe thanks to ON CONFLICT
    DO NOTHING on event_id.
    """
    parsed = 0
    inserted = 0
    last_ts: datetime | None = None
    last_event_id: uuid.UUID | None = None
    batch: list[dict[str, Any]] = []
    try:
        with open(path, "r", encoding="utf-8") as fh:
            for lineno, raw in enumerate(fh, start=1):
                row = _parse_line(raw, source_file=path.name, source_line=lineno)
                if row is None:
                    continue
                parsed += 1
                last_ts = row["ts"]
                last_event_id = row["event_id"]
                batch.append(row)
                if len(batch) >= batch_size:
                    inserted += await _insert_batch(session, batch)
                    batch.clear()
        if batch:
            inserted += await _insert_batch(session, batch)
        if last_ts is not None and last_event_id is not None:
            await _update_checkpoint(
                session,
                source_file=path.name,
                last_ts=last_ts,
                last_event_id=last_event_id,
            )
        await session.commit()
    except SQLAlchemyError:
        await session.rollback()
        raise
    return parsed, inserted


async def run_once() -> dict[str, int]:
    """Single end-to-end pass over the journal directory. Returns totals."""
    settings = get_settings()
    journal_dir = Path(settings.AURUM_JOURNAL_DIR)
    if not journal_dir.exists():
        logger.warning("etl: journal dir missing: %s", journal_dir)
        return {"parsed": 0, "inserted": 0, "files": 0}

    files = _list_journal_files(journal_dir)
    if not files:
        return {"parsed": 0, "inserted": 0, "files": 0}

    total_parsed = 0
    total_inserted = 0
    async with SessionLocal() as session:
        # Resume: start from checkpoint's file (or earliest) and walk forward.
        cp = await _load_checkpoint(session)
        start_idx = 0
        if cp and cp.last_processed_file:
            for i, p in enumerate(files):
                if p.name == cp.last_processed_file:
                    start_idx = i
                    break
        for path in files[start_idx:]:
            parsed, inserted = await _process_file(
                session, path, batch_size=settings.AURUM_ETL_BATCH_SIZE
            )
            total_parsed += parsed
            total_inserted += inserted
    return {
        "parsed": total_parsed,
        "inserted": total_inserted,
        "files": len(files) - start_idx,
    }


async def run_loop(stop_event: asyncio.Event | None = None) -> None:
    """Main background loop. Polls every AURUM_ETL_POLL_INTERVAL_SECONDS.

    Tolerates missing journal dir, malformed lines, and transient DB errors
    (with exponential backoff). Exits cleanly when stop_event is set.
    """
    settings = get_settings()
    backoff = 1.0
    while True:
        if stop_event is not None and stop_event.is_set():
            logger.info("etl: stop requested, exiting loop")
            return
        try:
            stats = await run_once()
            if stats["inserted"]:
                logger.info(
                    "etl: parsed=%d inserted=%d files=%d",
                    stats["parsed"],
                    stats["inserted"],
                    stats["files"],
                )
            backoff = 1.0  # success resets backoff
        except SQLAlchemyError as exc:
            logger.exception("etl: DB error, backing off %.1fs", backoff)
            await asyncio.sleep(backoff)
            backoff = min(backoff * 2, 30.0)
            continue
        except Exception:  # noqa: BLE001
            logger.exception("etl: unexpected error, backing off %.1fs", backoff)
            await asyncio.sleep(backoff)
            backoff = min(backoff * 2, 30.0)
            continue

        try:
            await asyncio.wait_for(
                stop_event.wait() if stop_event else asyncio.sleep(settings.AURUM_ETL_POLL_INTERVAL_SECONDS),
                timeout=settings.AURUM_ETL_POLL_INTERVAL_SECONDS,
            )
        except asyncio.TimeoutError:
            pass


async def get_etl_lag_seconds() -> float | None:
    """Returns (now - last_processed_ts) for /readyz health reporting.
    Returns None if no checkpoint yet."""
    async with SessionLocal() as session:
        cp = await session.get(EtlCheckpoint, ETL_SOURCE)
        if cp is None or cp.last_processed_ts is None:
            return None
        delta = datetime.now(timezone.utc) - cp.last_processed_ts
        return max(0.0, delta.total_seconds())
